### ISSUE TITLE
Implementing it in a sub UIView

### ISSUE THREAD

**Issue by lenichols** [yuppielabel/YPDrawSignatureView#6] opened 2016-03-02 23:13 UTC
I have a view that loads a pdf... YPDrawSignatureView doesn't work with something already in the view. What method would you suggest to either programmatically draw ontop of the current view or add the drawing above the view... in javascript land you can use z-index to layer. I get no errors, just do not see the drawing ontop of the pdf in the uiview. Thoughts? Comments? Help getting this to work?

**Comment by GJNilsen** [comment] 2016-03-04 19:41
Thats right, YPDrawSignatureView is a subclass of an UIView, and only it is supposed to populate its own view. So you can put it onto of another view and capture the stack if you want to save a signature thats embedded in the document.

**Comment by GJNilsen** [comment] 2016-03-06 13:35
Since this is not a bug, I'll close this topic.

**Closed as completed by GJNilsen** 2016-03-06 13:35 UTC
Labels: question
